---
apiVersion: stacks.crossplane.io/v1alpha1
kind: StackConfiguration

metadata:
  name: 'minimal-gcp'

spec:
  # The behaviors section is for configuring the template stack controller
  behaviors:
    engine:
      type: kustomize
    source:
      image: 'crossplaneio/minimal-gcp:latest'
    crds:
      MinimalGCP.gcp.resourcepacks.crossplane.io/v1alpha1:
        hooks:
          reconcile:
          - directory: resources/minimal-gcp

  title: "Minimal GCP Environment"
  readme: ""
  overview: "This stack provisions a private network and creates resource classes that has minimal node settings and refer to that private network."
  overviewShort: "Start using GCP with Crossplane without needing to create your own resource classes!"
  version: 1.0
  maintainers:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
  owners:
  - name: "Muvaffak Onus"
    email: "monus@upbound.io"
  company: "Upbound"
  category: "Environment Stack"
  keywords:
   - "easy"
   - "resource class"
   - "private network"
   - "cheap"
   - "minimal"
  website: "httos://upbound.io"
  source: "https://github.com/muvaf/minimal-gcp"
  permissionScope: Cluster
  dependsOn:
    - crd: '*.cache.gcp.crossplane.io/v1beta1'
    - crd: '*.compute.gcp.crossplane.io/v1alpha3'
    - crd: '*.database.gcp.crossplane.io/v1beta1'
    - crd: '*.storage.gcp.crossplane.io/v1alpha3'
    - crd: '*.servicenetworking.gcp.crossplane.io/v1alpha3'
    - crd: '*.gcp.crossplane.io/v1alpha3'
  # License SPDX name: https://spdx.org/licenses/
  license: Apache-2.0
